#! /bin/sh
config_home=${XDG_CONFIG_HOME:-$home/.config}
config=${config_home}/telekasten
export TELEKASTEN_SCRIPTS=${config}/scripts
. ${TELEKASTEN_SCRIPTS}/vars

# Load the needed scripts
needed() {
	[ -x "$1" ] || {
		echo 1>&2 "$1 either doesn't exist or is not executable"
		exit 1
	}
}
finder=${TELEKASTEN_SCRIPTS}/finder
needed $finder
format=${TELEKASTEN_SCRIPTS}/format
needed $format
index=${TELEKASTEN_SCRIPTS}/index
needed $index
host=${TELEKASTEN_SCRIPTS}/host
needed $host
watch=${TELEKASTEN_SCRIPTS}/watch
needed $watch

# Initialize the output directory
rm -rf "$TELEKASTEN_OUT"
mkdir -p "$TELEKASTEN_OUT"
cp -r "$config/static/"* "$TELEKASTEN_OUT"/

# Parallel replacements:
# {}: dir/subdir/file.ext
# {.}: dir/subdir/file
"$finder" | \
	parallel \
		"mkdir -p ${TELEKASTEN_OUT}/{//} && \
		${format} ${TELEKASTEN_ROOT}/{} > ${TELEKASTEN_OUT}/{.}.html"


"$index"
"$host" &
"$watch" | parallel "${format} ${TELEKASTEN_ROOT}/{} > ${TELEKASTEN_OUT}/{.}.html" &
