#! /bin/sh
# The finder script, should just print out every file its expecting to end up
# in the output

# This will cause find to print out the path's relative to the root
cd "$TELEKASTEN_ROOT" || exit 1
find "." \
	-name "*.md" \
	-type f \
	-not -path "./templates/*" \
	-not -path "./daily/*" |
	cut -b3-
